### ISSUE TITLE
Page won't scroll to the bottom.

### ISSUE THREAD

**Issue by JRProgramming** [catchatbot/web#19]
The page won't scroll to the bottom and the user is forced to scroll to the bottom. This needs to be fixed.

**Comment by Allen-B1** [comment]
Ok, I found this solution:
```js
div.scrollTop = div.scrollHeight
```

**Comment by Allen-B1** [comment]
I fixed it https://github.com/catchatbot/web/commit/5e0a5dcd4731298d797f138de21493d86b91b368
